author: Inacio Ferrarini
author_url: https://twitter.com/inacioferrarini
github_url: https://github.com/inacioferrarini/Common
root_url: https://inacioferrarini.github.io/Common/
module: Common
output: docs
theme: fullwidth
xcodebuild_arguments: [-workspace, 'Common.xcworkspace', -scheme, 'Common-iOS']
